<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Component_ServoMotor" Id="{7bc5585d-e043-4a4d-90c5-3748dca72298}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Component_ServoMotor IMPLEMENTS I_Component
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Halt" Id="{e670ceb9-7bbb-4f32-865f-4279a3ed37e2}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Halt : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{5850c2fb-1fd2-46fc-baa0-6de215783738}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{a7e4a841-9d33-4e88-80db-37d91db85604}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Component_ServoMotor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Component_ServoMotor.Halt">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Component_ServoMotor.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Component_ServoMotor.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>